// Code generated by "stringer -type=KeyType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SM-0]
	_ = x[ECDSA_R1-1]
	_ = x[ECDSA_K1-2]
}

const _KeyType_name = "SMECDSA_R1ECDSA_K1"

var _KeyType_index = [...]uint8{0, 2, 10, 18}

func (i KeyType) String() string {
	if i >= KeyType(len(_KeyType_index)-1) {
		return "KeyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyType_name[_KeyType_index[i]:_KeyType_index[i+1]]
}
